#!/bin/bash
palette="/tmp/palette.png"
filters="fps=15,scale=420:-1:flags=lanczos"

if [ "$1" != "" ];
then
  ffmpeg -i $1 -vf "$filters,palettegen" -y $palette
  ffmpeg -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y ~/Pictures/$1.gif
else
  echo "Missing video, try gif ~/Download/vide.mp4"
fi
